### ISSUE TITLE
older version?

### ISSUE THREAD

**Issue by sanderlanghorstredhotminute** [paynl/csharp-sdk#14]
Hi,
I see this SDK is based on v5 of the API, while the documentation on the website (https://www.pay.nl/docs/developers.php) is speaking of version 7.

Will this cause any problems in the future? Is there any progress for this SDK?

With kind regards

**Comment by sebastianberm** [comment]
Hi Sander,

This is not an issue. The development team of Pay adds new functions, this causes the API version to be updated sometimes. Old versions will stay supported or the SDK will be updated.
