### ISSUE TITLE
Static context

### ISSUE THREAD

**Issue by sanderlanghorstredhotminute** [paynl/csharp-sdk#15]
Hi,

I see the ApiToken and ServiceId are static. This will probably cause problems when using different ServiceIds, for different 'shops' in the same application, handeling concurrent requests.

The client should be instantiated with the ApiToken and ServiceId for that request.

With kind regards,

**Comment by KreativJos** [comment]
This indeed is a problem, especially while using multiple threads.

**Comment by woutse** [comment]
Thanks for your message. We are looking into this.
