### ISSUE TITLE
NuGet gallery link

### ISSUE THREAD

**Issue by marcinCzapiewski** [paynl/csharp-sdk#31]
Hi Pay.NL team. I'm starting integrating pay.nl with my customer's code and want to use this SDK, but I'm not sure which NuGet library is the official one and there are a few found in nuget gallery, but they seem to be forks. Could you add a link to proper NuGet in readme?

**Comment by woutse** [comment]
Here it is! https://www.nuget.org/packages/PayNLSdk/
